name: app_3
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^5.0.2
  # intl: ^0.19.0
  intl: any
  http: ^1.1.2
  encrypt: ^5.0.3
  path_provider: ^2.1.2
  open_file: ^3.3.2
  provider: ^6.1.2
  flutter_otp_text_field: ^1.2.0
  google_maps_flutter: ^2.7.1
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.4.1
  pinput: ^5.0.0
  flutter_bloc: ^8.1.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  flutter_facebook_auth: ^7.1.1
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  sqflite: ^2.4.1
  flutter_contacts: ^1.1.9+2
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # devtools: '>=0.9.4 <0.10.0'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/category/
    - assets/icons/profile/
    - assets/icons/on-boarding/
    - assets/icons/checkout/
    - assets/icons/social/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
