name: app_3
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  carousel_slider: ^5.0.0
  # intl: ^0.19.0
  intl: any
  http: ^1.1.2
  encrypt: ^5.0.3
  path_provider: ^2.1.2
  open_file: ^3.3.2
  provider: ^6.1.2
  flutter_otp_text_field: ^1.2.0
  google_maps_flutter: ^2.7.1
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  firebase_analytics: ^11.3.1
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # devtools: '>=0.9.4 <0.10.0'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/category/
    - assets/animations/
    - assets/icons/profile/
    - assets/icons/checkout/
    - assets/icons/
