// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7JhKa1a8xNKHfUw986_cTy_E_UdHP1j4',
    appId: '1:712803607053:android:8b72777821fcff3abaab44',
    messagingSenderId: '712803607053',
    projectId: 'e-learning-app-5f316',
    databaseURL: 'https://e-learning-app-5f316-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-learning-app-5f316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj5xz6kJkfNc5P-WDWNbgVpYsncSK89IY',
    appId: '1:712803607053:ios:e13bed7789d14841baab44',
    messagingSenderId: '712803607053',
    projectId: 'e-learning-app-5f316',
    databaseURL: 'https://e-learning-app-5f316-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-learning-app-5f316.firebasestorage.app',
    androidClientId: '712803607053-brnhb8jvahdaqst8of56sn6dmhur6r1v.apps.googleusercontent.com',
    iosClientId: '712803607053-90kg3nmak8en41q2qceb0dft1ac1d4sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasumai',
  );
}
