// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAIExwuR9igB7RwYPIxn0vjUysU-cQgHTQ',
//     appId: '1:712803607053:web:087f175894b090eebaab44',
//     messagingSenderId: '712803607053',
//     projectId: 'e-learning-app-5f316',
//     authDomain: 'e-learning-app-5f316.firebaseapp.com',
//     databaseURL: 'https://e-learning-app-5f316-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'e-learning-app-5f316.appspot.com',
//     measurementId: 'G-0KLKF2GNFH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBAA7DueyKUVkWglPobMJPMaSKal4m2ux0',
//     appId: '1:712803607053:android:85d4ae06f9fdb347baab44',
//     messagingSenderId: '712803607053',
//     projectId: 'e-learning-app-5f316',
//     databaseURL: 'https://e-learning-app-5f316-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'e-learning-app-5f316.appspot.com',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAj5xz6kJkfNc5P-WDWNbgVpYsncSK89IY',
//     appId: '1:712803607053:ios:ea3d7eec724a81f2baab44',
//     messagingSenderId: '712803607053',
//     projectId: 'e-learning-app-5f316',
//     databaseURL: 'https://e-learning-app-5f316-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'e-learning-app-5f316.appspot.com',
//     androidClientId: '712803607053-rolt886jv8lc5ucj1moa756cq2e0l4eb.apps.googleusercontent.com',
//     iosClientId: '712803607053-ao0vad4sgridkvqisfo6tuvv9fkuabfr.apps.googleusercontent.com',
//     iosBundleId: 'com.example.app3',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAIExwuR9igB7RwYPIxn0vjUysU-cQgHTQ',
//     appId: '1:712803607053:web:eed957f982fa34fabaab44',
//     messagingSenderId: '712803607053',
//     projectId: 'e-learning-app-5f316',
//     authDomain: 'e-learning-app-5f316.firebaseapp.com',
//     databaseURL: 'https://e-learning-app-5f316-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'e-learning-app-5f316.appspot.com',
//     measurementId: 'G-K3W91K6Q9L',
//   );
// }
